"""adding the chunk table in db

Revision ID: 56de8ce483e6
Revises: 738e03a45185
Create Date: 2026-01-03 14:56:37.529464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '56de8ce483e6'
down_revision: Union[str, Sequence[str], None] = '738e03a45185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rp_abstract_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.ForeignKeyConstraint(['rp_abstract_id'], ['BrieflyAI.RP_abstract_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rp_abstract_id', 'chunk_index', name='uq_chunks_rp_chunk'),
    schema='BrieflyAI'
    )
    op.create_index('idx_chunks_embedding', 'chunk_data', ['embedding'], unique=False, schema='BrieflyAI', postgresql_using='ivfflat')
    op.create_index('idx_chunks_rp_order', 'chunk_data', ['rp_abstract_id', 'chunk_index'], unique=False, schema='BrieflyAI')
    op.create_index(op.f('ix_BrieflyAI_chunk_data_doc_id'), 'chunk_data', ['doc_id'], unique=False, schema='BrieflyAI')
    op.create_index(op.f('ix_BrieflyAI_chunk_data_rp_abstract_id'), 'chunk_data', ['rp_abstract_id'], unique=False, schema='BrieflyAI')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BrieflyAI_chunk_data_rp_abstract_id'), table_name='chunk_data', schema='BrieflyAI')
    op.drop_index(op.f('ix_BrieflyAI_chunk_data_doc_id'), table_name='chunk_data', schema='BrieflyAI')
    op.drop_index('idx_chunks_rp_order', table_name='chunk_data', schema='BrieflyAI')
    op.drop_index('idx_chunks_embedding', table_name='chunk_data', schema='BrieflyAI', postgresql_using='ivfflat')
    op.drop_table('chunk_data', schema='BrieflyAI')
    # ### end Alembic commands ###
