"""create Research Paper Abstract along with metadata Table

Revision ID: 738e03a45185
Revises: 
Create Date: 2025-12-12 22:12:30.034910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '738e03a45185'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "BrieflyAI";')
    op.create_table('RP_abstract_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('published', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('all_categories', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('journal_ref', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link', name='uq_research_papers_link'),
    schema='BrieflyAI'
    )
    op.create_index('ix_research_papers_created_at', 'RP_abstract_data', ['created_at'], unique=False, schema='BrieflyAI')
    op.create_index('ix_research_papers_primary_category', 'RP_abstract_data', ['primary_category'], unique=False, schema='BrieflyAI')
    op.create_index('ix_research_papers_published', 'RP_abstract_data', ['published'], unique=False, schema='BrieflyAI')
    op.create_index('ix_research_papers_summary_trgm', 'RP_abstract_data', ['summary'], unique=False, schema='BrieflyAI', postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
    op.create_index('ix_research_papers_title_trgm', 'RP_abstract_data', ['title'], unique=False, schema='BrieflyAI', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RP_abstract_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('authors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('all_categories', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doi', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('journal_ref', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('RP_abstract_data_pkey')),
    sa.UniqueConstraint('link', name=op.f('uq_research_papers_link'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('ix_research_papers_title_trgm', table_name='RP_abstract_data', schema='BrieflyAI', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_research_papers_summary_trgm', table_name='RP_abstract_data', schema='BrieflyAI', postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
    op.drop_index('ix_research_papers_published', table_name='RP_abstract_data', schema='BrieflyAI')
    op.drop_index('ix_research_papers_primary_category', table_name='RP_abstract_data', schema='BrieflyAI')
    op.drop_index('ix_research_papers_created_at', table_name='RP_abstract_data', schema='BrieflyAI')
    op.drop_table('RP_abstract_data', schema='BrieflyAI')
    # ### end Alembic commands ###
