"""add the Abstract Chunk table

Revision ID: 92ed848952cc
Revises: 56de8ce483e6
Create Date: 2026-01-18 14:40:17.193187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '92ed848952cc'
down_revision: Union[str, Sequence[str], None] = '56de8ce483e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paperAbstractChunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rp_abstract_id', sa.UUID(), nullable=False),
    sa.Column('pdf_url', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.ForeignKeyConstraint(['rp_abstract_id'], ['BrieflyAI.RP_abstract_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rp_abstract_id', 'chunk_index', name='uq_abstract_rp_chunk'),
    schema='BrieflyAI'
    )
    op.create_index('idx_paper_abstract_chunks_embedding', 'paperAbstractChunk', ['embedding'], unique=False, schema='BrieflyAI', postgresql_using='ivfflat')
    op.create_index('idx_paper_abstract_chunks_rp_order', 'paperAbstractChunk', ['rp_abstract_id', 'chunk_index'], unique=False, schema='BrieflyAI')
    op.create_index(op.f('ix_BrieflyAI_paperAbstractChunk_pdf_url'), 'paperAbstractChunk', ['pdf_url'], unique=False, schema='BrieflyAI')
    op.create_index(op.f('ix_BrieflyAI_paperAbstractChunk_rp_abstract_id'), 'paperAbstractChunk', ['rp_abstract_id'], unique=False, schema='BrieflyAI')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BrieflyAI_paperAbstractChunk_rp_abstract_id'), table_name='paperAbstractChunk', schema='BrieflyAI')
    op.drop_index(op.f('ix_BrieflyAI_paperAbstractChunk_pdf_url'), table_name='paperAbstractChunk', schema='BrieflyAI')
    op.drop_index('idx_paper_abstract_chunks_rp_order', table_name='paperAbstractChunk', schema='BrieflyAI')
    op.drop_index('idx_paper_abstract_chunks_embedding', table_name='paperAbstractChunk', schema='BrieflyAI', postgresql_using='ivfflat')
    op.drop_table('paperAbstractChunk', schema='BrieflyAI')
    # ### end Alembic commands ###
