"""create intent vector table

Revision ID: b55b5240d19f
Revises: 92ed848952cc
Create Date: 2026-01-18 18:46:12.403710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
from app.settings import get_settings

# revision identifiers, used by Alembic.
revision: str = 'b55b5240d19f'
down_revision: Union[str, Sequence[str], None] = '92ed848952cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    vector_dim = get_settings().embedding_vector_dim
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_vectors',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=vector_dim), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    schema='BrieflyAI'
    )
    op.add_column('chunk_data', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True), schema='BrieflyAI')
    op.add_column('paperAbstractChunk', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True), schema='BrieflyAI')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paperAbstractChunk', 'created_at', schema='BrieflyAI')
    op.drop_column('chunk_data', 'created_at', schema='BrieflyAI')
    op.drop_table('intent_vectors', schema='BrieflyAI')
    # ### end Alembic commands ###
