"""adding the LLM summary column

Revision ID: d885caa91e0e
Revises: b55b5240d19f
Create Date: 2026-01-20 16:43:30.172552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd885caa91e0e'
down_revision: Union[str, Sequence[str], None] = 'b55b5240d19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_data', sa.Column('llm_summary', sa.Text(), nullable=True), schema='BrieflyAI')
    op.alter_column('chunk_data', 'rp_abstract_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='BrieflyAI')
    op.add_column('paperAbstractChunk', sa.Column('llm_summary', sa.Text(), nullable=True), schema='BrieflyAI')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paperAbstractChunk', 'llm_summary', schema='BrieflyAI')
    op.alter_column('chunk_data', 'rp_abstract_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='BrieflyAI')
    op.drop_column('chunk_data', 'llm_summary', schema='BrieflyAI')
    # ### end Alembic commands ###
